version: '2.1'

services:

  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        - YII_ENV=${YII_ENV}
    image: 'app_test:1.0'
    env_file:
      - .env
      - .env.local
    ports:
      - ${APP_PORT:-80}:80
    volumes:
      - .:/app:delegated
    depends_on:
      - postgres

  postgres:
    image: postgres:13.1
    restart: always
    env_file:
      - .env
      - .env.local
    volumes: 
      - ./docker/postgres:/docker-entrypoint-initdb.d
